# PostgreSQL 연결 설정
spring.datasource.url=jdbc:postgresql://localhost:5432/rememory
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 카카오 redirect-uri
spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8080/login/oauth2/code/kakao

# SQL 로그
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

firebase.enabled=false