#rds
spring.datasource.url=${RDS_URL}
spring.datasource.username=${RDS_USER}
spring.datasource.password=${RDS_PASSWORD}

#카카오 redirect-uri
spring.security.oauth2.client.registration.kakao.redirect-uri=https://api.rememory.me/login/oauth2/code/kakao

#app.frontend-url
app.frontend-url=https://rememory.me